### ISSUE TITLE
feature request.

### ISSUE THREAD

**Issue by ghost** [Zeunig/lol_clipboard#1]
we copy paste in chat to keep in mind the duration of the summoner spells, but sometimes we need to use translator etc. to communicate more properly with the team and this is where the confusion comes in, when you do ctrl v it gives like this:
flash 900 [text from clipboard]

**Comment by Zeunig** [comment]
Hi :D
I just added the ability to customize your keybinds, download the newest version of the program and check it out.
Thanks for the suggestion

**Comment by ghost** [comment]
Hi!
Works like a charm! Thanks for adding this feature as light speed.

**Comment by Zeunig** [comment]
No problem, enjoy! ^^
